-- Migración de datos: 30 fundaciones + 4 solicitudes urgentes
-- Ejecutar en: https://supabase.com/dashboard/project/uboswvsijbddwygypkic/sql/new

INSERT INTO fundaciones (nombre, descripcion, categoria, localidad, web, email, acepta_dinero, acepta_especies, acepta_voluntarios, certificado_tributario, verificada, beneficiarios, año_fundacion) VALUES
('Fundación PLAN Colombia',       'Más de 60 años promoviendo derechos de la niñez en situación de vulnerabilidad extrema.',                    'ninez',          'Bogotá',          'plan.org.co',                    'info@plan.org.co',                           true,  false, true,  false, true, 'Miles de niños en 6 departamentos', 1964),
('Fundación Niñas de Luz',        'Acompaña niñas y adolescentes en Bogotá para fortalecer su liderazgo y proyectos de vida.',                  'ninez',          'Bogotá',          'funiluz.org',                    'info@funiluz.org',                           true,  true,  true,  false, true, 'Niñas y adolescentes',             2013),
('Fundación Sentires',            'Trabaja con 60 niños en Ciudad Bolívar. Recibe útiles, alimentos y voluntarios.',                            'ninez',          'Ciudad Bolívar',  'fundacionsentires.org',          'info@fundacionsentires.org',                 true,  true,  true,  false, true, '+300 niños y familias',            2010),
('Fundación Ecosueños',           'Internado ICBF para niños y adolescentes cuyos derechos han sido vulnerados en Bogotá.',                     'ninez',          'Bogotá',          'fundacionecosuenos.org',         'info@fundacionecosuenos.org',                true,  true,  true,  false, true, 'Niños en protección ICBF',         2014),
('Fundación Casa de Colombia',    'Salud y educación para niños. Facilita acceso a tratamientos médicos especializados.',                       'ninez',          'Bogotá',          'casadecolombia.co',              'info@casadecolombia.co',                     true,  false, true,  false, true, 'Niños con enfermedades',           2005),
('Fundación Laudes Infantis',     'Beneficia 300 familias con roperos comunitarios y refrigerios para niños y adultos mayores.',                 'ninez',          'Bogotá',          'laudesinfantis.org',             'info@laudesinfantis.org',                    true,  true,  true,  false, true, '+300 familias',                    2008),
('Fundación Levántate y Anda',    'Educación, recreación y acompañamiento a niños y adolescentes vulnerables en Bogotá.',                       'ninez',          'Bogotá',          'fundacionlevantateyanda.org',    'info@fundacionlevantateyanda.org',            true,  true,  true,  true,  true, 'Niños y adolescentes',             2005),
('Fundación Líderes Monarca',     'Educación y protección a niños y jóvenes vulnerables en Bogotá. Acepta voluntarios.',                        'educacion',      'Bogotá',          'fundacionlideresmonarca.org',    'info@fundacionlideresmonarca.org',            true,  true,  true,  false, true, 'Jóvenes en vulnerabilidad',        2012),
('Fundación Fundevi',             '10 años apoyando educación, salud y necesidades básicas. Más de 500 beneficiarios.',                         'educacion',      'Bogotá',          'fundacionfundevi.org',           'info@fundacionfundevi.org',                  true,  true,  true,  false, true, '+500 personas',                    2014),
('Fundación Asómate',             'Entrega ropa a más de 900 personas en Ciudad Bolívar, Usme y Santa Fe cada mes.',                            'educacion',      'Ciudad Bolívar',  'asomate.org',                    'info@asomate.org',                           false, true,  true,  false, true, '+900 personas mensuales',          2018),
('Fundación Eudes',               'ONG en Bogotá que atiende población vulnerable. Expide certificados de donación tributarios.',                'educacion',      'Engativá',        'fundacioneudes.co',              'direccionadministrativa@fundacioneudes.co',  true,  true,  true,  true,  true, 'Familias vulnerables',             2003),
('Colitas Felices',               'Rescata perros en situación de maltrato. Esterilizaciones por $80.000. Acepta PSE y tarjeta.',               'animales',       'Chocontá/Bogotá', 'colitasfelices.org',             'info@colitasfelices.org',                    true,  true,  true,  false, true, '+1.100 animales',                  2018),
('Fundación Gatitus',             'Rescate y adopción de gatos abandonados. Aprobada DIAN. Donantes deducen 25% en renta.',                     'animales',       'Bogotá',          'fundaciongatitusuv.org',         'info@fundaciongatitusuv.org',                true,  true,  true,  true,  true, 'Gatos rescatados',                 2018),
('Fundación Mil Bigotes',         'Más de 2.000 gatos impactados desde 2016. Meta: 300 rescates, esterilizaciones y adopciones anuales.',       'animales',       'Bogotá',          'milbigotes.com',                 'info@milbigotes.com',                        true,  true,  true,  false, true, '+2.000 gatos',                     2016),
('Fundación TEPA',                'Rescate y adopción responsable de animales. Recibe alimentos, medicinas y cobijas.',                         'animales',       'Bogotá',          'fundaciontepa.org',              'info@fundaciontepa.org',                     true,  true,  true,  false, true, 'Perros y gatos rescatados',        2010),
('Asoanimales Colombia',          'Rescata perros y gatos abandonados, les da atención integral en salud y los da en adopción.',                 'animales',       'Bogotá',          'asoanimales.org',                'info@asoanimales.org',                       true,  true,  true,  false, true, 'Animales rescatados',              2003),
('Fundación La Manuelita',        'Desde 1915 ofrece vida digna a adultos mayores en pobreza. 50 residentes y 80 voluntarios.',                 'adultosMayores', 'Cajicá/Bogotá',   'lamanuelita.org',                'info@lamanuelita.org',                       true,  true,  true,  false, true, '50 adultos mayores',               1915),
('FUNDAMA',                       'Desde 1977. Cinco sedes en Bogotá con 320 apartamentos para mayores de 65 años.',                            'adultosMayores', 'Suba/Usaquén',    'fundama.com.co',                 'info@fundama.com.co',                        true,  false, true,  false, true, '320 adultos mayores',              1977),
('Fundación Juan Pablo II',       'Desde 1978 en Bogotá. Cuida adultos mayores vulnerables con programas de bienestar.',                        'adultosMayores', 'Bogotá',          'fundacionjuanpabloii.com',       'info@fundacionjuanpabloii.com',              true,  true,  true,  false, true, 'Adultos mayores vulnerables',      1978),
('Fundación Provida Colombia',    'Nutrición, educación y acompañamiento a adultos mayores. Red Solidaria con voluntariado.',                   'adultosMayores', 'Bogotá',          'fundacionprovida.org',           'info@fundacionprovida.org',                  true,  true,  true,  false, true, 'Adultos mayores',                  2000),
('Fundación Humedales Bogotá',    'Más de 30.000 árboles sembrados en 6 años. Certificados tributarios. Jornadas de reforestación.',           'medioAmbiente',  'Bogotá',          'humedalesbogota.com',            'info@humedalesbogota.com',                   true,  false, true,  true,  true, 'Ecosistemas bogotanos',            2015),
('Fundación Natura Colombia',     'ONG ambiental líder. Conservación de ecosistemas, reforestación y áreas protegidas en Colombia.',           'medioAmbiente',  'Bogotá',          'natura.org.co',                  'info@natura.org.co',                         true,  false, true,  true,  true, 'Ecosistemas naturales',            1984),
('Trébola Ecológica',             'Educación ambiental desde 2004. Más de 120.000 personas capacitadas en Bogotá en reciclaje.',               'medioAmbiente',  'Bogotá',          'trebola.org',                    'info@trebola.org',                           false, false, true,  false, true, '+120.000 personas',                2004),
('Banco de Alimentos de Bogotá',  'Redistribuye alimentos a comunidades vulnerables. Red ABACO. Certificados tributarios.',                    'medioAmbiente',  'Bogotá',          'abaco.org.co',                   'info@abaco.org.co',                          true,  true,  true,  true,  true, 'Miles de familias',                1990),
('Fundación Santa Fe de Bogotá',  'Décadas de trayectoria en salud. Reinvierte cada recurso. Expide certificados de donación.',                'salud',          'Usaquén',         'fundacionsantafedebogota.com',   'donaciones@fsfb.org.co',                     true,  false, true,  true,  true, 'Pacientes y comunidad',            1972),
('Fundación CIREC',               'Rehabilitación integral para personas con discapacidad. Metodología de Sanación Integral.',                 'salud',          'Bogotá',          'fundacioncirec.org',             'info@fundacioncirec.org',                    true,  false, true,  false, true, 'Personas con discapacidad',        1990),
('Fundación ICAL',                'Salud y rehabilitación en Bogotá. Acepta voluntarios según sus saberes y disponibilidad.',                  'salud',          'Bogotá',          'icalcolombia.org',               'info@icalcolombia.org',                      true,  true,  true,  false, true, 'Pacientes en rehabilitación',      1995),
('Fundación Saldarriaga Concha',  '50 años construyendo una Colombia inclusiva para personas con discapacidad y adultos mayores.',             'discapacidad',   'Bogotá',          'saldarriagaconcha.org',          'info@saldarriagaconcha.org',                 true,  false, true,  true,  true, 'Personas con discapacidad',        1973),
('Fundación Manos al Cielo',      'Apoya personas con discapacidad y sus cuidadores con talleres, cursos y nutrición comunitaria.',            'discapacidad',   'Bogotá',          'fundacionmanosalcielo.org',      'info@fundacionmanosalcielo.org',             true,  true,  true,  false, true, 'Personas con discapacidad',        2015),
('Fundación CREINSER',            'Inclusión laboral, educativa y social de personas con discapacidad en Bogotá y Cundinamarca.',              'discapacidad',   'Bogotá',          'fundacioncreinser.com',          'info@fundacioncreinser.com',                 true,  true,  true,  false, true, 'Personas con discapacidad',        2008);

-- Solicitudes urgentes vinculadas a fundaciones reales
INSERT INTO solicitudes (fundacion_id, titulo, tipo, urgencia, meta, progreso, fecha_limite, activa)
SELECT id, 'Útiles escolares para 60 niños en Ciudad Bolívar', 'money', 'alta', 4500000, 3240000, '2026-06-14', true
FROM fundaciones WHERE nombre = 'Fundación Sentires';

INSERT INTO solicitudes (fundacion_id, titulo, tipo, urgencia, meta, progreso, fecha_limite, activa)
SELECT id, 'Jornada de reforestación: 500 árboles nativos', 'money', 'media', 6000000, 2750000, '2026-06-20', true
FROM fundaciones WHERE nombre = 'Fundación Humedales Bogotá';

INSERT INTO solicitudes (fundacion_id, titulo, tipo, urgencia, meta, progreso, fecha_limite, activa)
SELECT id, 'Ropa de abrigo para 50 adultos mayores', 'clothes', 'alta', 200, 130, '2026-06-13', true
FROM fundaciones WHERE nombre = 'Fundación La Manuelita';

INSERT INTO solicitudes (fundacion_id, titulo, tipo, urgencia, meta, progreso, fecha_limite, activa)
SELECT id, 'Dotación de libros para biblioteca comunitaria', 'books', 'media', 400, 260, '2026-06-17', true
FROM fundaciones WHERE nombre = 'Fundación Fundevi';

-- Verificar resultado
SELECT 'fundaciones' AS tabla, COUNT(*) AS total FROM fundaciones
UNION ALL
SELECT 'solicitudes', COUNT(*) FROM solicitudes;
